rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/general_schema_documentation/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_linux/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_fucshia/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_macos/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_server/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_apis/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_android/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_ios/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_client/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_dart/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_assets_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_web/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_flutter/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_isar_scheme/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_cli/LICENSE
rm -f /home/galaxeus/Documents/private_library/general_private_tools/templates/general_schema/package/general_schema_windows/LICENSE
