name: 'general_schema_project'
description: 'General Schema is library for styling your schema for all project language for help you get best perfect style '
version: '0.0.0'
homepage: 'https://www.youtube.com/@GENERALCORP'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@GENERALCORP'
funding:
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.68'
  packagex: '^1.0.0'
  path: '^1.9.0'
  yaml: '^3.1.3'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
project:
  type: ''
