name: Schedule

on:
    # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 */1 * * *"}]
    # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:

permissions:
  contents: write

jobs:
  general_schema_gpa:
    name: Package Template Poject GPA
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            plan_type: 'regular'
          - os: ubuntu-24.04
            plan_type: 'premium'
          - os: ubuntu-24.04
            plan_type: 'ultra'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 1

      - name: Install Dependencies 
        shell: bash
        run: | 
          sudo apt update -y
          sudo apt-get install -y wget

      - name: Install Programs
          
        shell: bash
        run: | 
          wget https://github.com/archivon-apps-stores/general_public_action/releases/download/stable/general_public_action.deb
          sudo dpkg --force-all -i ./general_public_action.deb
   
      - name: Install Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
         channel: stable
         flutter-version: 3.27.0
         cache: true

      - name: Running General Public Action ${{ matrix.plan_type }}
        shell: bash
        run: |
          gpa --command ${{ matrix.plan_type }}
